package constants

const (
	// Internal server error codes
	INTERNAL_SERVER_ERROR_CODE            = "INTERNAL_SERVER_ERROR"
	LOCATION_SEARCH_PROCESSING_ERROR_CODE = "LOCATION_SEARCH_PROCESSING_ERROR"
	// Unprocessable entity codes
	UNPROCESSABLE_ENTITY_CODE           = "UNPROCESSABLE_ENTITY"
	INVALID_API_KEY_PERMISSION_CODE     = "INVALID_API_KEY_PERMISSION"
	INVITATION_REVOKED_CODE             = "INVITATION_REVOKED"
	INVITATION_EXPIRED_CODE             = "INVITATION_EXPIRED"
	INVITATION_ALREADY_ACCEPTED_CODE    = "INVITATION_ALREADY_ACCEPTED"
	INVALID_INVITATION_TOKEN_CODE       = "INVALID_INVITATION_TOKEN"
	USER_ALREADY_MEMBER_CODE            = "USER_ALREADY_MEMBER"
	MISSING_PADDLE_CUSTOMER_ID_CODE     = "MISSING_PADDLE_CUSTOMER_ID"
	MISSING_PADDLE_SUBSCRIPTION_ID_CODE = "MISSING_PADDLE_SUBSCRIPTION_ID"
	SUBSCRIPTION_CHANGE_FAILED_CODE     = "SUBSCRIPTION_CHANGE_FAILED"
	DOWNGRADE_NOT_ALLOWED_CODE          = "DOWNGRADE_NOT_ALLOWED"
	CURRENT_PASSWORD_MISMATCH_CODE      = "CURRENT_PASSWORD_MISMATCH"
	// Conflict codes
	CONFLICT_CODE                       = "CONFLICT"
	API_KEY_ALREADY_REVOKED_CODE        = "API_KEY_ALREADY_REVOKED"
	EMAIL_ALREADY_VERIFIED_CODE         = "EMAIL_ALREADY_VERIFIED"
	EMAIL_ALREADY_IN_USE_CODE           = "EMAIL_ALREADY_IN_USE"
	PADDLE_CUSTOMER_ALREADY_EXISTS_CODE = "PADDLE_CUSTOMER_ALREADY_EXISTS"
	ROLE_HAS_MEMBERS_CODE               = "ROLE_HAS_MEMBERS"
	RESOURCE_ALREADY_ARCHIVED_CODE      = "RESOURCE_ALREADY_ARCHIVED"
	RESOURCE_NOT_ARCHIVED_CODE          = "RESOURCE_NOT_ARCHIVED"
	// Not found codes
	NOT_FOUND_CODE         = "NOT_FOUND"
	PASSWORD_MISMATCH_CODE = "PASSWORD_MISMATCH"
	// Unauthorized codes (auth: access/refresh tokens, API key)
	UNAUTHORIZED_CODE                  = "UNAUTHORIZED"
	INVALID_TOKEN_CODE                 = "INVALID_TOKEN"
	EXPIRED_TOKEN_CODE                 = "EXPIRED_TOKEN"
	AUTHORIZATION_HEADER_REQUIRED_CODE = "AUTHORIZATION_HEADER_REQUIRED"
	INVALID_API_KEY_CODE               = "INVALID_API_KEY"
	// Unauthorized codes (verify email token)
	INVALID_VERIFICATION_TOKEN_CODE = "INVALID_VERIFICATION_TOKEN"
	EXPIRED_VERIFICATION_TOKEN_CODE = "EXPIRED_VERIFICATION_TOKEN"
	// Unauthorized codes (password reset token)
	INVALID_PASSWORD_RESET_TOKEN_CODE = "INVALID_PASSWORD_RESET_TOKEN"
	EXPIRED_PASSWORD_RESET_TOKEN_CODE = "EXPIRED_PASSWORD_RESET_TOKEN"
	// Bad request codes
	BAD_REQUEST_CODE                   = "BAD_REQUEST"
	LOCATION_SEARCH_INVALID_QUERY_CODE = "LOCATION_SEARCH_INVALID_QUERY"
	// Forbidden codes
	FORBIDDEN_CODE                     = "FORBIDDEN"
	FEATURE_NOT_AVAILABLE_CODE         = "FEATURE_NOT_AVAILABLE"
	ORGANIZATION_SEATS_LIMIT_CODE      = "ORGANIZATION_SEATS_LIMIT"
	LOCATION_SEARCH_DENIED_CODE        = "LOCATION_SEARCH_DENIED"
	USER_CANNOT_REMOVE_OWN_MEMBER_CODE = "USER_CANNOT_REMOVE_OWN_MEMBER"
	USER_CANNOT_UPDATE_OWN_MEMBER_CODE = "USER_CANNOT_UPDATE_OWN_MEMBER"
	ROLE_LOCKED_CODE                   = "ROLE_LOCKED"
	INVITATION_EMAIL_MISMATCH_CODE     = "INVITATION_EMAIL_MISMATCH"
	// Payment required codes
	PAYMENT_REQUIRED_CODE     = "PAYMENT_REQUIRED"
	FEATURE_NOT_INCLUDED_CODE = "FEATURE_NOT_INCLUDED"
	// Too many requests codes
	TOO_MANY_REQUESTS_CODE               = "TOO_MANY_REQUESTS"
	LOCATION_SEARCH_TEMPORARY_ERROR_CODE = "LOCATION_SEARCH_TEMPORARY_ERROR"
	// Service unavailable codes
	SERVICE_UNAVAILABLE_CODE         = "SERVICE_UNAVAILABLE"
	LOCATION_SEARCH_UNAVAILABLE_CODE = "LOCATION_SEARCH_UNAVAILABLE"
)
