package constants

const (
	SUBSCRIPTION_TYPE_FREE = iota
	SUBSCRIPTION_TYPE_BASIC
	SUBSCRIPTION_TYPE_PRO
	SUBSCRIPTION_TYPE_ENTERPRISE
)

const (
	PAYMENT_INTERVAL_MONTHLY = 0
	PAYMENT_INTERVAL_ANNUAL  = 1
)

const (
	SUBSCRIPTION_TYPE_SEATS_INCLUDED_FREE       = 1
	SUBSCRIPTION_TYPE_SEATS_INCLUDED_BASIC      = 3
	SUBSCRIPTION_TYPE_SEATS_INCLUDED_PRO        = 10
	SUBSCRIPTION_TYPE_SEATS_INCLUDED_ENTERPRISE = -1

	SUBSCRIPTION_TRIAL_DAYS = 30

	// SUBSCRIPTION_PAST_DUE_GRACE_DAYS is how many days after subscription expiry we still allow access (past-due grace). After this, PAYMENT_REQUIRED is returned.
	SUBSCRIPTION_PAST_DUE_GRACE_DAYS = 7
)

const (
	AUDIT_LOG_RETENTION_DAYS_FREE       = 0
	AUDIT_LOG_RETENTION_DAYS_BASIC      = 90
	AUDIT_LOG_RETENTION_DAYS_PRO        = 365
	AUDIT_LOG_RETENTION_DAYS_ENTERPRISE = -1
)

const (
	FEATURE_AUDIT_LOG  = "audit_log"
	FEATURE_API_ACCESS = "api_access"
	FEATURE_ROLES      = "roles"
	FEATURE_TEAMS      = "teams"
)

var FEATURES_FOR_PLANS = map[string][]int{
	FEATURE_AUDIT_LOG: {
		SUBSCRIPTION_TYPE_BASIC,
		SUBSCRIPTION_TYPE_PRO,
		SUBSCRIPTION_TYPE_ENTERPRISE,
	},
	FEATURE_API_ACCESS: {
		SUBSCRIPTION_TYPE_PRO,
		SUBSCRIPTION_TYPE_ENTERPRISE,
	},
	FEATURE_ROLES: {
		SUBSCRIPTION_TYPE_PRO,
		SUBSCRIPTION_TYPE_ENTERPRISE,
	},
	FEATURE_TEAMS: {
		SUBSCRIPTION_TYPE_PRO,
		SUBSCRIPTION_TYPE_ENTERPRISE,
	},
}

var AuditLogRetentionDaysByType = map[int]int{
	SUBSCRIPTION_TYPE_FREE:       AUDIT_LOG_RETENTION_DAYS_FREE,
	SUBSCRIPTION_TYPE_BASIC:      AUDIT_LOG_RETENTION_DAYS_BASIC,
	SUBSCRIPTION_TYPE_PRO:        AUDIT_LOG_RETENTION_DAYS_PRO,
	SUBSCRIPTION_TYPE_ENTERPRISE: AUDIT_LOG_RETENTION_DAYS_ENTERPRISE,
}
